language: rust
cache: cargo
dist: trusty
sudo: true
services:
- docker

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - zlib1g-dev

# Run builds in Linux, MacOS X and Windows
os:
- linux
- osx
- windows

# Run builds for all the supported trains
rust:
- 1.31.0
- stable
- beta
- nightly

stages:
- test
- deploy

# Extra jobs to include
jobs:
  include:
  # Test package generation for multiple distributions
  - os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=DEBIAN
    script: ./travis-helper.sh dist_test debian
  - os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=UBUNTU
    script: ./travis-helper.sh dist_test ubuntu
  - os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=FEDORA
    script: ./travis-helper.sh dist_test fedora
  - os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=CENTOS
    script: ./travis-helper.sh dist_test centos
  # Upload documentation
  - os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      github-token: $GITHUB_TOKEN
      local-dir: target/doc/*
      skip_cleanup: true
      keep-history: true
      on:
        repo: SUPERAndroidAnalyzer/super
        branch: develop
  # Deploy the release
  - os: linux
    rust: false
    stage: deploy
    env: CACHE_NAME=DEPLOY
    script: ./travis-helper.sh deploy
    deploy: &releases
      provider: releases
      api_key:
        secure: n19EgLXHFh8pXBulAfOFtzIMFPSm0yM0yi/sXY1bQgr+QztAHwxkGKaCU/y4yqYwDNH0hCFQn+P8X//Yucz/Cvw2Ng2G040hMJqsu/RztX5svq+pjmTNYX9QuwOg/6AnFoQs2zxRMZia4npVDA66q78G5GA+2eKZ/cDc5/6M32uh7RH8d6yYDnyCJ1lOk35tFu7DLZtfC5xQvOeC+iD4QIiKtVitcjRLQPiV71cG42a0wYYjX3sVKCjqF7NX/q5VHLxG0EofaLeyAI2NdK9RkuAfd6y8YyR0XNwlvq0qX8j5iDtc6ljzOtytlPYUlvyF3AqOJdVt+rBiI2/tZDtVkOobO+hS/+Tl680PpiX+m/HaHErgV0pMYCavYQkjPyMVE0DJCMTMCoHFhGMB+gC/piagVBZ9lKFHRgxXYBFhJVoco2vqMZDm85avI7IzL9YNtJqRt0h2JJZ4/42/Hn0+52CtXJI86HwUU4hD0eUsm9yyWNOsrDahmra1H28vxS7fjEb1Sozol3fMRWKMllKqsUr8Xd06wePqtfYow0ufdHTcumQte9Ls11hgZhDSMd7g6P9tPL5P0UeWa3x8xjNk6Lx3ghAVfzF2CePkeg4VQSHMonZEhaIxShdkCl3Z30F4DOe0p6Pq6ZsG6RRA4/qoIYGPvchfAC4L+VaWjC7yQ0k=
      file: releases/*
      skip_cleanup: true
      prerelease: true # TODO: remove on 1.0
      on:
        repo: SUPERAndroidAnalyzer/super
        tags: true

matrix:
  allow_failures:
  - os: windows

before_script:
- export PATH=$PATH:~/.cargo/bin
  # TODO: change tag when bumping version number. (Maintain in sync with Cargo.toml)
- |
  if [[ $TRAVIS_TAG ]]; then
    export TAG=$TRAVIS_TAG;
  else
    export TAG="0.5.0";
  fi

# Run the multiple tests.
script:
- ./travis-helper.sh fmt_run
- ./travis-helper.sh clippy_run
- ./travis-helper.sh test
- ./travis-helper.sh test_ignored
- ./travis-helper.sh build_unstable
- ./travis-helper.sh test_unstable
- ./travis-helper.sh test_unstable_ignored

# Upload code coverage report
after_success:
- ./travis-helper.sh upload_code_coverage

notifications:
  email:
    recipients:
    - razican@protonmail.ch
    - brunoop@protonmail.ch
    - sergiodlo@protonmail.com
    - jaimesr@protonmail.ch
    on_success: change
    on_failure: always
