language: rust
cache: cargo
dist: xenial
sudo: true

# Run builds in Linux, MacOS X and Windows
os:
- linux
- osx
- windows

# Run builds for all the supported trains
rust:
- 1.31.0
- stable
- beta
- nightly

stages:
- test
- deploy

# Extra jobs to include
jobs:
  include:
  # Test package generation for multiple distributions
  - name: "Debian packaging"
    os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=DEBIAN
    services: docker
    script: ./travis-helper.sh dist_test debian
  - name: "Ubuntu packaging"
    os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=UBUNTU
    services: docker
    script: ./travis-helper.sh dist_test ubuntu
  - name: "Fedora packaging"
    os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=FEDORA
    services: docker
    script: ./travis-helper.sh dist_test fedora
  - name: "CentOS packaging"
    os: linux
    rust: stable
    stage: test
    env: CACHE_NAME=CENTOS
    services: docker
    script: ./travis-helper.sh dist_test centos
  # Test unstable features
  - name: "Unstable features"
    os: linux
    rust: nightly
    stage: test
    env: CACHE_NAME=UNSTABLE
    services: docker
    script: ./travis-helper.sh test_unstable
  # Upload documentation
  - name: "Documentation upload"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      github-token: $GH_TOKEN
      local-dir: target/doc/
      skip_cleanup: true
      keep-history: true
      on:
        repo: SUPERAndroidAnalyzer/super
        branch: develop
  # Deploy the release
  - name: "Release deployment"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DEPLOY
    script: ./travis-helper.sh deploy
    deploy: &releases
      provider: releases
      api_key: $GH_TOKEN
      file: releases/*
      skip_cleanup: true
      prerelease: true # TODO: remove on 1.0
      name: "SUPER $TRAVIS_TAG"
      on:
        repo: SUPERAndroidAnalyzer/super
        tags: true

matrix:
  allow_failures:
  - os: windows

before_script:
- export PATH=$PATH:~/.cargo/bin
  # TODO: change tag when bumping version number. (Maintain in sync with Cargo.toml)
- |
  if [[ $TRAVIS_TAG ]]; then
    export TAG=$TRAVIS_TAG;
  else
    export TAG="0.5.1";
  fi

# Run the multiple tests.
script:
- ./travis-helper.sh fmt_check
- ./travis-helper.sh clippy_check
- ./travis-helper.sh test
- ./travis-helper.sh test_ignored

# Upload code coverage report
after_success:
- ./travis-helper.sh upload_code_coverage

notifications:
  email:
    recipients:
    - razican@protonmail.ch
    - brunoop@protonmail.ch
    - sergiodlo@protonmail.com
    - jaimesr@protonmail.ch
    on_success: change
    on_failure: always
