[package]
name = "super-analyzer"
version = "0.4.1"
authors = [
    "Iban Eguia <razican@protonmail.ch>",
    "Jaime Salas <jaimesr@protonmail.ch>",
    "Bruno Pin <brunoop@protonmail.ch>",
    "Sergio de los Dolores <sergiodlo@protonmail.com>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/SUPERAndroidAnalyzer/super"
homepage = "http://superanalyzer.rocks"
description = """\
Secure, Unified, Powerful and Extensible Rust Android Analyzer. Core software\
with CLI.\
"""
keywords = ["Android", "security", "audit", "super", "analyzer"]
categories = ["command-line-utilities", "development-tools"]

[badges]
travis-ci = { repository = "SUPERAndroidAnalyzer/super", branch = "master" }
appveyor = { repository = "Razican/super", branch = "master", service = "github" }
codecov = { repository = "SUPERAndroidAnalyzer/super", branch = "master", service = "github" }
is-it-maintained-issue-resolution = { repository = "SUPERAndroidAnalyzer/super" }
is-it-maintained-open-issues = { repository = "SUPERAndroidAnalyzer/super" }

[[bin]]
name = "super-analyzer"
path = "src/main.rs"

[lib]
name = "super_analyzer_core"
path = "src/lib.rs"

[dependencies]
clap = "2.29.2"
xml-rs = "0.7.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
chrono = { version = "0.4.0", features = ["serde"] }
toml = "0.4.5"
regex = "0.2.5"
lazy_static = "1.0.0"
open = "1.2.1"
bytecount = "0.3.0"
log = "0.4.1"
env_logger = "0.5.0"
error-chain = "0.11.0"
md5 = "0.3.6"
sha1 = "0.6.0"
sha2 = "0.7.0"
abxml = "0.3.0"
handlebars = "0.32.0"
semver = "0.9.0"
hex = "0.3.1"

[target.'cfg(windows)'.dependencies]
colored = { version = "1.6.0", features = ["no-color"] }

[target.'cfg(not(windows))'.dependencies]
colored = "1.6.0"

[build-dependencies]
clap = "2.29.2"

[dev-dependencies]
reqwest = "0.8.4"

[features]
default = ["beta"]
beta = []
unstable = ["beta", "certificate"]
certificate = []

[package.metadata.deb]
maintainer = "Iban Eguia <razican@protonmail.ch>"
copyright = "2016, Iban Eguia <razican@protonmail.ch>"
license_file = ["LICENSE", "0"]
extended_description = """\
Secure, Unified, Powerful and Extensible Rust Android Analyzer. Core software\
with CLI."""
depends = "libc6, libgcc1, default-jre-headless, bash"
section = "devel"
priority = "optional"
assets = [
    # Executable
    ["target/release/super-analyzer", "usr/bin/", "755"],
    # Completion scripts
    ["target/release/super.bash-completion", "usr/share/bash-completion/completions/", "755"],
    ["target/release/super.fish", "usr/share/fish/vendor_completions.d/", "755"],
    ["target/release/_super", "usr/share/zsh/vendor-completions/", "755"],
    # JD-CMD
    ["vendor/jd-cmd.jar", "usr/share/super-analyzer/vendor/", "755"],
    ["vendor/jd-cmd.LICENSE.txt", "usr/share/super-analyzer/vendor/", "644"],
    # Dex2Jar
    ["vendor/dex2jar-2.1-SNAPSHOT/LICENSE.txt", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/", "644"],
    ["vendor/dex2jar-2.1-SNAPSHOT/NOTICE.txt", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/", "644"],
    ["vendor/dex2jar-2.1-SNAPSHOT/d2j-dex2jar.sh", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/d2j_invoke.sh", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/antlr-runtime-3.5.2.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/asm-debug-all-4.1.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/d2j-base-cmd-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/d2j-jasmin-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/d2j-smali-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/dex-ir-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/dex-reader-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/dex-reader-api-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/dex-tools-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/dex-translator-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/dex-writer-2.1-SNAPSHOT.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    ["vendor/dex2jar-2.1-SNAPSHOT/lib/dx-1.7.jar", "usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT/lib/", "755"],
    #CSS
    ["templates/super/css/androidstudio.css", "usr/share/super-analyzer/templates/super/css/", "644"],
    ["templates/super/css/style.css", "usr/share/super-analyzer/templates/super/css/", "644"],
    # Images
    ["templates/super/img/folder-icon.png", "usr/share/super-analyzer/templates/super/img/", "644"],
    ["templates/super/img/java-icon.png", "usr/share/super-analyzer/templates/super/img/", "644"],
    ["templates/super/img/xml-icon.png", "usr/share/super-analyzer/templates/super/img/", "644"],
    ["templates/super/img/report.png", "usr/share/super-analyzer/vendor/results_template/img/", "644"],
    ["templates/super/img/logo.svg", "usr/share/super-analyzer/templates/super/img/", "644"],
    # JavaScript
    ["templates/super/js/highlight.js.LICENSE", "usr/share/super-analyzer/templates/super/js/", "644"],
    ["templates/super/js/highlight.pack.js", "usr/share/super-analyzer/templates/super/js/", "644"],
    ["templates/super/js/jquery-3.2.0.slim.min.js", "usr/share/super-analyzer/templates/super/js/", "644"],
    ["templates/super/js/src_nav.js", "usr/share/super-analyzer/templates/super/js/", "644"],
    # templates
    ["templates/super/code.hbs", "usr/share/super-analyzer/templates/super/", "644"],
    ["templates/super/report.hbs", "usr/share/super-analyzer/templates/super/", "644"],
    ["templates/super/src.hbs", "usr/share/super-analyzer/templates/super/", "644"],
    ["templates/super/vulnerability.hbs", "usr/share/super-analyzer/templates/super/", "644"],
    # Config
    ["rules.json", "etc/super-analyzer/", "644"],
    ["config.toml", "etc/super-analyzer/", "644"],
    ["config.toml.sample", "etc/super-analyzer/", "644"],
    # README
    ["README.md", "usr/share/doc/super-analyzer/README.md", "644"],
]

# The release profile, used for `cargo build`.
[profile.dev]
incremental = true
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
panic = 'unwind'

# The release profile, used for `cargo build --release`.
[profile.release]
incremental = false
opt-level = 3
debug = false
rpath = false
codegen-units = 1
lto = true
debug-assertions = false
panic = 'unwind'
