[package]
name = "super"
version = "0.1.0"
authors = [
    "Iban Eguia <razican@protonmail.ch>",
    "Jaime Salas <jaimesr@protonmail.ch>",
    "Bruno Pin <brunoop@protonmail.ch>",
    "Sergio de los Dolores <sergiodlo@protonmail.com>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/SUPERAndroidAnalyzer/super"
description = """
Secure, Unified, Powerful and Extensible Rust Android Analyzer. Core software
with CLI.
"""
keywords = ["Android", "security", "audit", "super", "analyzer"]

[dependencies]
clap = "^2.11"
colored = "^1.3"
zip = "^0.1"
xml-rs = "^0.3"
serde = "^0.8"
serde_json = "^0.8"
yaml-rust = "0.3"
chrono = "^0.2"
toml = "^0.2"
regex = "^0.1"
rust-crypto = "^0.2"
rustc-serialize = "^0.3"

# The release profile, used for `cargo build`.
[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
panic = 'unwind'

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'unwind'
